version: '2.1'

services:
    tm1:
        build:
            context: docker
            dockerfile: Dockerfile-tema2
        privileged: true
        depends_on:
            - "tm2"
        volumes:
            - .:/elocal
        tty: true
        networks:
            - dmz
        command: bash -c "python elocal/src/udp_client.py --server tm2 --port 1000 --mesaj salut"
    tm2:
        build:
            context: docker
            dockerfile: Dockerfile-tema2
        privileged: true
        volumes:
            - .:/elocal
        tty: true
        networks:
            - dmz
        command: bash -c "tcpdump -i any -vvv -nn ip and udp & python elocal/src/udp_server.py --port 1000"

networks:
    dmz: {}
